version: "3"
services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: 
    - "9200:9200"
    environment: 
    - "discovery.type=single-node"
    - "bootstrap.memory_lock=true"
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    depends_on:
    - elasticsearch
    ports:
    - "5601:5601"
    environment: 
    - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"